### ISSUE TITLE
Export installer.ps1 as the release object

### ISSUE THREAD

**Issue by Fixstars-momoko** [Sensing-Dev/sensing-dev-installer#21]
Currently for each release we have 
- package (msi)
- package (zip)
- source code (zip)
- source code (tar)

and we ask users to use installer/tools/installer.ps1 to automatically DL package files.

I would like to add installer.ps1 as one of the release object as well so that each release look like this:

- installer.ps1
- package (msi)
- package (zip)
- source code (zip)
- source code (tar)

**Comment by fixstars-sonali** [comment]
Update job Release

```
- name: Release      
        uses: softprops/action-gh-release@v1
        with:
          files: |
            installer/tools/installer.ps1
            installer/build/*.msi
            installer/build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
