### ISSUE TITLE
Update install-Winusb script 

### ISSUE THREAD

**Issue by fixstars-sonali** [Sensing-Dev/sensing-dev-installer#33]
Update Download URL latest WinUSB-installer-generator to https://github.com/Sensing-Dev/WinUSB-installer-generator/releases/

**Comment by fixstars-sonali** [comment]
@Fixstars-momoko Would you please make repo https://github.com/Sensing-Dev/WinUSB-installer-generator public. The installer script will not download the package if it's a private repo.

**Comment by Fixstars-momoko** [comment]
@fixstars-sonali I just made it public, thanks!
