### ISSUE TITLE
Aravis dependencies management by vcpkg on windows environment

### ISSUE THREAD

**Issue by iitaku** [Sensing-Dev/sensing-dev-installer#51]
I confirmed that Aravis is successfully built on Windows without conan by following steps.

### Setup tools

Python 3.11 and pkg-config is required to build Aravis with vcpkg.

```
winget install Python.Python.3.11 bloodrock.pkg-config-lite
```

### Setup vcpkg

The gobject-introspection port is required to be patched. [PR](https://github.com/microsoft/vcpkg/pull/36279) is waiting for the upstream merge. Meanwhile, please use my branch.

```
git clone -b fix-gobject-introspection https://github.com/iitaku/vcpkg.git
cd vcpkg
.\bootstrap-vcpkg.bat
```

###  Install dependencies

Install aravis dependencies from vcpkg manifest (vcpkg.json). vcpkg.json is better to be located in aravis source tree. [PR](https://github.com/Sensing-Dev/aravis/pull/1) is here.

```
git clone -b feature/setup-dependencies-by-vcpkg https://github.com/iitaku/aravis.git
cd aravis
<path-to-vcpkg.exe> install
```

Dependencies will be installed in `vcpkg_installed`. 

### Build aravis
```
set PATH=%CD%\vcpkg_installed\x64-windows\bin;%CD%\vcpkg_installed\x64-windows\tools\gobject-introspection;%PATH%
set PKG_CONFIG_PATH=%CD%\vcpkg_installed\x64-windows\lib\pkgconfig\
meson setup -Ddocumentation=disabled -Dusb=enabled -Dviewer=disabled -Dgv-n-buffers=1 -Dprefix=./install -Dintrospection=enabled ./build .
meson compile -C ./build
meson install -C ./install
```

### Packaging

vcpkg_installed/x64-windows/bin contains all DLLs and .pyd file. Probably it is better to minimize which one is required at runtime to create a package for the sensing-dev installer. 

### Setup 

Install MSVC command line tools to setup PyGobject through pip.

```
winget install Microsoft.VisualStudio.2022.BuildTools --silent --override "--wait --quiet --add ProductLang En-us --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended
```

### Install PyGObject

PyPI package is old. Install from git.

```
pip install --config-settings=setup-args="-Dtests=false" git+https://gitlab.gnome.org/GNOME/pygobject.git@3653581164a9b71f706447838ae488db4a9a677e
```

All set!

**Comment by Fixstars-momoko** [comment]
## Setup vcpkg

@iitaku 

* For vcpkg, branch name `fix-gobject-introspection` is not found in your repository of forked 
* For Aravis, branch name `feature/setup-dependencies-by-vcpkg` is not found in your repository of forked (is it okay to use the upstream?)

**Comment by iitaku** [comment]
@Fixstars-momoko 

> For vcpkg, branch name fix-gobject-introspection is not found in your repository of forked

It's already [merged](https://github.com/microsoft/vcpkg/pull/36279) to upstream and my branch was deleted. Please just use upstream.

> For Aravis, branch name feature/setup-dependencies-by-vcpkg is not found in your repository of forked (is it okay to use the upstream?)

Can you see [this](https://github.com/iitaku/aravis/tree/feature/setup-dependencies-by-vcpkg)?

**Comment by Fixstars-momoko** [comment]
Note:

```
error: no version database entry for gobject-introspection at 1.72.0#7.
Available versions:
  1.72.0#6
  1.72.0#5
  1.72.0#4
  1.72.0#3
  1.72.0#2
  1.72.0#1
  1.72.0
  1.70.0#1
  1.70.0
See `vcpkg help versioning` or https://learn.microsoft.com/vcpkg/users/versioning for more information.
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

tentatively replaced with version 1.72.0#6

**Comment by iitaku** [comment]
@Fixstars-momoko Which version (git commit hash) of vcpkg are you using? `1.72.0#7` is the one which I made change and you must have it.

**Comment by Fixstars-momoko** [comment]
@iitaku I was replacing it with `1.72.0#6` and now facing the issue of gobject introspection. where can I fetch the database? I was using vcpkg upstream

**Comment by iitaku** [comment]
@Fixstars-momoko vcpkg manage all package information on the git. Please make sure to run `git fetch` to get latest vcpkg version from github.

**Comment by Fixstars-momoko** [comment]
@iitaku No, sorry I just checked the remote URL and that was yours. I will replace the URL to 
https://github.com/microsoft/vcpkg.git

**Comment by Fixstars-momoko** [comment]
meson @iitaku was using  1.3.1

**Comment by xinyuli1204** [comment]
@Fixstars-momoko @iitaku  i repeat the steps.

## Build Aravis

### Setup tools

Python 3.11 and pkg-config is required to build Aravis with vcpkg.

```
winget install Python.Python.3.11 bloodrock.pkg-config-lite
```
**PASSED**

### Setup vcpkg

The gobject-introspection port is required to be patched. [PR](https://github.com/microsoft/vcpkg/pull/36279) is waiting for the upstream merge. Meanwhile, please use my branch.

```
git clone https://github.com/microsoft/vcpkg.git
cd vcpkg
.\bootstrap-vcpkg.bat
```
**PASSED**


###  Install dependencies

Install aravis dependencies from vcpkg manifest (vcpkg.json). vcpkg.json is better to be located in aravis source tree. [PR](https://github.com/Sensing-Dev/aravis/pull/1) is here.

```
git clone -b feature/setup-dependencies-by-vcpkg https://github.com/iitaku/aravis.git
cd aravis
<path-to-vcpkg.exe> install
```

Dependencies will be installed in `vcpkg_installed`. 

**PASSED**

### Build aravis
```
set PATH=%CD%\vcpkg_installed\x64-windows\bin;%CD%\vcpkg_installed\x64-windows\tools\gobject-introspection;%PATH%
set PKG_CONFIG_PATH=%CD%\vcpkg_installed\x64-windows\lib\pkgconfig\
```
~~meson setup -Ddocumentation=disabled -Dusb=enabled -Dviewer=disabled -Dgv-n-buffers=1 -Dprefix=./install -Dintrospection=enabled ./build .~~


meson.build:1:0: ERROR: prefix value './install' must be an absolute path
meson.build:1:0: ERROR: prefix value './build' must be an absolute path 
`meson setup -Ddocumentation=disabled -Dusb=enabled -Dviewer=disabled -Dgv-n-buffers=1 -Dprefix=F:\dev\aravis\install -Dintrospection=enabled build .`

**PASSED**

` meson compile -C ./build`
shows error
```
--- stderr ---
Traceback (most recent call last):
  File "F:\dev\aravis\vcpkg_installed\x64-windows\lib\gobject-introspection\giscanner\pkgconfig.py", line 34, in check_output
    return subprocess.check_output(argv, universal_newlines=True, stderr=subprocess.STDOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Python\Python311\Lib\subprocess.py", line 465, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Python\Python311\Lib\subprocess.py", line 546, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Python\Python311\Lib\subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Python\Python311\Lib\subprocess.py", line 1491, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\dev\aravis\vcpkg_installed\x64-windows\tools\gobject-introspection\g-ir-scanner", line 101, in <module>
    dll_dirs.add_dll_dirs(['gio-2.0'])
  File "F:\dev\aravis\vcpkg_installed\x64-windows\lib\gobject-introspection\giscanner\utils.py", line 310, in add_dll_dirs
    for path in giscanner.pkgconfig.libs_only_L(pkgs, True):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\dev\aravis\vcpkg_installed\x64-windows\lib\gobject-introspection\giscanner\pkgconfig.py", line 59, in libs_only_L
    out = check_output(flags, ignore_errors, command)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\dev\aravis\vcpkg_installed\x64-windows\lib\gobject-introspection\giscanner\pkgconfig.py", line 42, in check_output
    raise PkgConfigError('pkg-config: error executing command %s: %s' % (argv, e))
giscanner.pkgconfig.PkgConfigError: pkg-config: error executing command ['"C:\\Users\\Xinyu Li\\AppData\\Local\\Microsoft\\WinGet\\Packages\\bloodrock.pkg-config-lite_Microsoft.Winget.Source_8wekyb3d8bbwe\\pkg-config-lite-0.28-1\\bin\\pkg-config.EXE"', '--static', '--libs-only-L', 'gio-2.0']: [WinError 5] Access is denied

[141/150] Linking target tests/arv-acquisiti
```
also run with administration command line.

fixed it by install python and bloodrock to F:/, since default path has blank space
~~winget install Python.Python.3.11 bloodrock.pkg-config-lite~~
```
winget uninstall Python.Python.3.11 bloodrock.pkg-config-lite
winget install Python.Python.3.11  --location F:\dev\Python.Python.3.11
winget install Pbloodrock.pkg-config-lite  --location F:\dev\bloodrock.pkg-config-lite
```
~~meson install -C ./install~~
meson install -C  ./build

Packaging
vcpkg_installed/x64-windows/bin contains all DLLs and .pyd file. Probably it is better to minimize which one is required at runtime to create a package for the sensing-dev installer.
**PASSED**

### Use Aravis from Python
Setup
Install MSVC command line tools to setup PyGobject through pip.
```
winget install Microsoft.VisualStudio.2022.BuildTools --silent --override "--wait --quiet --add ProductLang En-us --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended
Install PyGObject
```
**PASSED**
PyPI package is old. Install from git.
```
pip install --config-settings=setup-args="-Dtests=false" git+https://gitlab.gnome.org/GNOME/pygobject.git@3653581164a9b71f706447838ae488db4a9a677e
```
**PASSED**

**Comment by Fixstars-momoko** [comment]
This note for build aravis with vcpkg-dependencies helped to complete CICD build with gobject introspection for MSVC https://github.com/Sensing-Dev/aravis/actions/runs/8333617437

Thank you so much @iitaku @xinyuli1204
